from pathlib import Path

path = Path('pages/2_🌿_Vegetation_Monitoring.py')
text = path.read_text(encoding='utf-8')

anchor = '''    # Clickable information layer for the rendered vegetation web map.\n    # The raster remains the 100 m web display derived from the native 10 m analysis.\n    # Popup attributes intentionally come from the 250 m Spatial Overview summary.\n    info_data = safe_spatial_features()'''
replacement = '''    # Clickable information layers for NDVI and NDMI.\n    # The rendered web map remains a 100 m raster derived from the native 10 m analysis.\n    # Click popups use the retained 250 m Spatial Overview summary as the attribute source.\n    info_data = safe_spatial_features()\n    if info_data.get("features"):\n        def add_index_popup_layer(layer_name, title, fields, aliases):\n            popup = folium.GeoJsonPopup(\n                fields=fields, aliases=aliases, localize=True, labels=True, sticky=False,\n                max_width=360, style="background-color: white;",\n            )\n            tooltip = folium.GeoJsonTooltip(\n                fields=fields[:3], aliases=aliases[:3], localize=True, sticky=False, labels=True,\n            )\n            folium.GeoJson(\n                info_data,\n                name=layer_name,\n                style_function=lambda _: {\n                    "fillColor": "#ffffff", "fillOpacity": 0.001, "color": "#ffffff",\n                    "weight": 0, "opacity": 0,\n                },\n                highlight_function=lambda _: {\n                    "fillColor": "#ffffff", "fillOpacity": 0.10, "weight": 1,\n                    "color": "#ffffff", "opacity": 0.35,\n                },\n                tooltip=tooltip, show=True,\n            ).add_child(popup).add_to(m)\n\n        add_index_popup_layer(\n            "🌿 NDVI · click for value",\n            "NDVI",\n            ["ndvi", "analysis_year", "analysis_start", "analysis_end", "observed_pct", "temporal_fallback_pct", "spatial_interpolation_pct"],\n            ["NDVI", "Analysis Year", "Analysis Start", "Analysis End", "Directly Observed (%)", "Temporal Fallback (%)", "Spatial Interpolation (%)"],\n        )\n        add_index_popup_layer(\n            "💧 NDMI · click for value",\n            "NDMI",\n            ["ndmi", "analysis_year", "analysis_start", "analysis_end", "observed_pct", "temporal_fallback_pct", "spatial_interpolation_pct"],\n            ["NDMI", "Analysis Year", "Analysis Start", "Analysis End", "Directly Observed (%)", "Temporal Fallback (%)", "Spatial Interpolation (%)"],\n        )'''
if anchor not in text:
    raise SystemExit('popup anchor not found')
text = text.replace(anchor, replacement, 1)
path.write_text(text, encoding='utf-8')
print('NDVI/NDMI popup layers added.')
